# Array module

In [39]:
import array

In [40]:
# Creation
arr1 = array.array("i", [1, 2, 3, 4, 5])
arr1

array('i', [1, 2, 3, 4, 5])

In [41]:
# Accessing elements
arr1[2]     # Third element

3

In [42]:
# Traverse the array
for element in arr1:
    print(element, end=" ")

1 2 3 4 5 

In [43]:
# Insertion
arr1.append(35)     # Appends the element in the last
arr1

array('i', [1, 2, 3, 4, 5, 35])

In [44]:
arr1.insert(5, 20)
arr1

array('i', [1, 2, 3, 4, 5, 20, 35])

In [45]:
# Deletion
arr1.remove(20)     # Removes 20 (only removes the first occurrence)

In [46]:
arr1

array('i', [1, 2, 3, 4, 5, 35])

In [47]:
# Update
arr1[3] = 40
arr1

array('i', [1, 2, 3, 40, 5, 35])

In [48]:
# Sorting
arr2 = array.array("i", [60, 17, 19, 35, 44, 29])
sorted(arr2)

[17, 19, 29, 35, 44, 60]

In [49]:
# Merging
print(arr1)
print(arr2)
arr4 = arr1 + arr2  # merging
print(arr4)

array('i', [1, 2, 3, 40, 5, 35])
array('i', [60, 17, 19, 35, 44, 29])
array('i', [1, 2, 3, 40, 5, 35, 60, 17, 19, 35, 44, 29])


In [50]:
# Splitting


# Numpy

In [51]:
import numpy as np

In [52]:
# Creation

np1 = np.array([10, 20, 30, 40, 50])
np2 = np.array([50, 60, 70])

print(np1)
print(np2)

[10 20 30 40 50]
[50 60 70]


In [53]:
# Access
np1[1]

np.int64(20)

In [54]:
# Traversal
for element in np1:
    print(element)

10
20
30
40
50


In [55]:
# Insertion
np.insert(np1, 2, 100)

array([ 10,  20, 100,  30,  40,  50])

In [56]:
# Deletion
np.delete(np1, 4)

array([10, 20, 30, 40])

In [57]:
# Updation
np1[0] = 250
np1

array([250,  20,  30,  40,  50])

In [58]:
# Sorting
np.sort(np1)

array([ 20,  30,  40,  50, 250])

In [59]:
# Merging
print(np1)
print(np2)

[250  20  30  40  50]
[50 60 70]


In [60]:
combined_array = np.concatenate((np1, np2))
combined_array

array([250,  20,  30,  40,  50,  50,  60,  70])

In [64]:
# Splitting
split1, split2 = np.array_split(combined_array, 2)
print(split1)
print(split2)

[250  20  30  40]
[50 50 60 70]


In [65]:
# Vectorization
np1

array([250,  20,  30,  40,  50])

In [66]:
np1 + 10

array([260,  30,  40,  50,  60])

In [67]:
np1 * 20

array([5000,  400,  600,  800, 1000])

In [71]:
np4 = np.arange(1, 7)
np5 = np.arange(11, 17)
print(np4)
print(np5)

[1 2 3 4 5 6]
[11 12 13 14 15 16]


In [72]:
np5 / np4

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ,
        2.66666667])